ProyectoWeb/ProyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Germinar.urls')),
    path('api/', include('rest_germinar.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('carro/', include('carro.urls')),
    path('pedidos/', include('pedidos.urls')),
    path('suscripcion/', include('suscripcion.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ProyectoWeb/carro/urls.py
from django.urls import path
from .import views

app_name= "carro"

urlpatterns = [
    path("agregar/<int:idProducto>/",views.agregar_producto, name="agregar"),
    path("add/<int:idProducto>/",views.agregar_producto_cart, name="add"),
    path("eliminar/<int:idProducto>/",views.eliminar_producto, name="eliminar"),
    path("restar/<int:idProducto>/",views.restar_producto, name="restar"),
    path("limpiar/",views.limpiar_carro, name="limpiar"),
]

ProyectoWeb/suscripcion/urls.py
from django.urls import path
from .views import ListaMembresia, MembresiaView 

app_name= "suscripcion"

urlpatterns = [
    path('', ListaMembresia.as_view(), name='seleccionar'),
    path('confirmar', MembresiaView, name='confirmar')
]

ProyectoWeb/suscripcion/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save

User= get_user_model()

# Create your models here.
class Membresia(models.Model):
    TIPO_MEMBRESIA = (
        ('Gratis', 'free'),
        ('Germinar', 'ger')
    )

    slug = models.SlugField()
    tipoMembresia = models.CharField(choices=TIPO_MEMBRESIA, max_length=30, default='Gratis')
    precioMemebresia = models.IntegerField(default=3000)

    def __str__(self):
        return self.tipoMembresia

class UserMembresia(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    tipoMembresia = models.ForeignKey(Membresia, on_delete=models.SET_NULL,  default='Gratis', null=True)

    def __str__(self):
        return self.user.username

def post_save_usermembresia_create(sender, instance, created, *args, **kwargs):
    if created:
        UserMembresia.objects.get_or_create(user=instance)

    userMembresia, created = UserMembresia.objects.get_or_create(user=instance)

post_save.connect(post_save_usermembresia_create, sender=User)

class Suscripcion(models.Model):
    userMembresia = models.ForeignKey(UserMembresia, on_delete=models.CASCADE)
    estado = models.BooleanField(default=True)

    def __str__(self):
        return self.userMembresia.user.username

ProyectoWeb/suscripcion/views.py
from msilib.schema import ListView
from multiprocessing import context
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views.generic import ListView
from .models import Membresia, Suscripcion, UserMembresia
from django.contrib import messages
# Create your views here.

def get_user_membership(request):
    userMembresia = UserMembresia.objects.filter(user=request.user)
    if userMembresia.exists():
        return userMembresia.first()
    return None

def get_user_subscription(request):
    suscripcion_user = Suscripcion.objects.filter(
        userMembresia = get_user_membership(request)
    )
    if suscripcion_user.exists():
        userSuscripcion = suscripcion_user.first()
        return userSuscripcion
    return None

def get_selected_membership(request):
    tipoMembresia = request.session['tipo_membresia_seleccionada']
    membresia_seleccionada_qs = Membresia.objects.filter(
        tipoMembresia = tipoMembresia
    )
    if membresia_seleccionada_qs.exists():
        return membresia_seleccionada_qs.first()
    return None




class ListaMembresia(ListView):
    model = Membresia

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        membresia_actual = get_user_membership(self.request)
        context['membresia_actual'] = str(membresia_actual.tipoMembresia)
        return context

    def post(self, request, **kwargs):
        tipo_membresia_seleccionada = request.POST.get('tipoMembresia')
        membresia_user = get_user_membership(request)
        suscripcion_user = get_user_subscription(request)
        membresia_seleccionada_qs = Membresia.objects.filter(
            tipoMembresia = tipo_membresia_seleccionada
        )
        if membresia_seleccionada_qs.exists():
            membresia_seleccionada = membresia_seleccionada_qs.first()

        if membresia_user.tipoMembresia == membresia_seleccionada:
            if suscripcion_user != None:
                messages.info(request, "Ya tienes esta membresía")
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        request.session['tipo_membresia_seleccionada']=membresia_seleccionada.tipoMembresia

        return HttpResponseRedirect('confirmar')


def MembresiaView(request):
    membresia_user = get_user_membership(request)
    membresia_seleccionada = get_selected_membership(request)
    print(membresia_user)

    if request.method == "POST":
        try:
            membresia_user.tipoMembresia = membresia_seleccionada
            membresia_user.save()
            sub, created = Suscripcion.objects.get_or_create(UserMembresia=membresia_user)

        except:
            pass
    context = {
        'membresia_seleccionada': membresia_seleccionada
    }

    return render(request, "suscripcion/membresia_check.html", context)

ProyectoWeb/suscripcion/templates/suscripcion/membresia_check.html
{% extends "Germinar/base.html" %}
{% block title %} Membresia_confirmar {% endblock %}
<!DOCTYPE html>
{% block content %}
{% load crispy_forms_tags %}
{% load static %} 
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Membresia_confirmar</title>
</head>
<body>
    <div class="contenedor-form">
        <div class="contenedor3">
            <div class="subt-pago">
                <h2>Confirmar Suscripcion</h2>
            </div>
            <br>
            <br>
            <h2>Suscripcion elegida: {{ membresia_seleccionada }}</h2>
            <form href="" method="POST">
                {% csrf_token %}
                <input type="submit" value="{{ membresia_seleccionada }}" class="card-link">
            </form>
        </div>
    </div>
</body>
</html>
{% endblock %}

ProyectoWeb/suscripcion/templates/suscripcion/membresia_list.html
{% extends "Germinar/base.html" %}
{% block title %} Suscripcion {% endblock %}
<!DOCTYPE html>
{% block content %}
{% load crispy_forms_tags %}
{% load static %} 
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Suscripcion</title>
    <link type="text/css" rel="preload" href="{% static 'Germinar/css/diseno.css' %}">
    <link type="text/css" rel="stylesheet" href ="{% static 'Germinar/css/diseno.css' %}">
    <link type="text/css" rel="preload" href="{% static 'Germinar/css/normalize.css' %}"> <!--Ayudará en normalizar la vista de la página para todos los navegadores, asi no habrá distinciones entre abrir la página en diferentes navegadores-->
    <link type="text/css" rel="stylesheet" href="{% static 'Germinar/css/normalize.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css" />
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js"></script>
</head>
<body>
    <section class="donaciones" id="donaciones">
        <div class="cuadro-donaciones contenedor2" >
            <div class="titulo-donacion">
                <h1>Colabora con nosotros</h1>
            </div>
            {% for object in object_list %}
            <div class="card" style="width: 25rem;">
                <div class="card-body">
                    <h5 class="card-title">Suscripci&oacute;n {{ object.tipoMembresia }}</h5>
                    <p class="card-text"> ${{ object.precioMemebresia }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-leaf" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="#1F4550" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                        <path d="M5 21c.5 -4.5 2.5 -8 7 -10" />
                        <path d="M9 18c6.218 0 10.5 -3.288 11 -12v-2h-4.014c-9 0 -11.986 4 -12 9c0 1 0 3 2 5h3z" />
                        </svg> Lorem ipsum dolor sit amet</li>
                    <li class="list-group-item"><svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-leaf" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="#1F4550" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                        <path d="M5 21c.5 -4.5 2.5 -8 7 -10" />
                        <path d="M9 18c6.218 0 10.5 -3.288 11 -12v-2h-4.014c-9 0 -11.986 4 -12 9c0 1 0 3 2 5h3z" />
                        </svg> Lorem ipsum dolor sit amet</li>
                    <li class="list-group-item"><svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-leaf" width="20" height="20" viewBox="0 0 24 24" stroke-width="1.5" stroke="#1F4550" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                        <path d="M5 21c.5 -4.5 2.5 -8 7 -10" />
                        <path d="M9 18c6.218 0 10.5 -3.288 11 -12v-2h-4.014c-9 0 -11.986 4 -12 9c0 1 0 3 2 5h3z" />
                        </svg> Lorem ipsum dolor sit amet</li>
                </ul>
                {% if object.tipoMembresia != 'free' %}
                <form method="POST" action="{% url 'suscripcion:seleccionar' %}">
                    {% csrf_token %}
                    {% if object.tipoMembresia != membresia_actual %}
                        <div class="card-bottom card-body">
                            <button class="card-link">Colabora ahora</button>
                        </div>
                    {% else %}
                        <div class="card-bottom card-body">
                            <h1> Esta es tu membresia </h1>
                        </div>
                    {% endif %}
                    <div class="card-bottom card-body">
                        <input type="hidden" href="#" name="tipoMembresia" value="{{ object.tipoMembresia }}" class="card-link">
                    </div>
                </form>
                {% endif %}
            </div>
            {% endfor %}
        </div>
    </section><!--DONACIONES-->
</body>
</html>
{% endblock %}