ProyectoWeb/Germinar/urls.py
from django.urls import path
from . import views
from .views import agregarProducto, eliminarProducto, formulario, principal, listaProductos, seguimiento, base, planta, carrito, actualizarProducto, formulario

urlpatterns = [
    path('home', views.Home.as_view(), name='Home'),
    path('formulario', formulario, name='formulario'),
    path('seguimiento', seguimiento, name='seguimiento'),
    path('planta/<int:id>', planta, name='planta'),
    path('base', base, name='base'),
    path('carrito', carrito, name='carrito'),
    path('', principal, name='principal'),
    path('listadoProductos', listaProductos, name='listaProductos'),
    path('agregarProducto', agregarProducto, name='agregarProducto'),
    path('actualizarProducto/<int:id>', actualizarProducto, name='actualizarProducto'),
    path('eliminarProducto/<int:id>', eliminarProducto, name='eliminarProducto'),
]

ProyectoWeb/ProyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Germinar.urls')),
    path('api/', include('rest_germinar.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('carro/', include('carro.urls')),
    path('pedidos/', include('pedidos.urls')),
    path('suscripcion/', include('suscripcion.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ProyectoWeb/carro/urls.py
from django.urls import path
from .import views

app_name= "carro"

urlpatterns = [
    path("agregar/<int:idProducto>/",views.agregar_producto, name="agregar"),
    path("add/<int:idProducto>/",views.agregar_producto_cart, name="add"),
    path("eliminar/<int:idProducto>/",views.eliminar_producto, name="eliminar"),
    path("restar/<int:idProducto>/",views.restar_producto, name="restar"),
    path("limpiar/",views.limpiar_carro, name="limpiar"),
]

ProyectoWeb/Germinar/models.py
from random import choices
from tkinter import CASCADE
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token


# Create your models here.
class catProducto(models.Model):
    idCategoria = models.IntegerField(primary_key=True, verbose_name= 'Id Categoria')
    nombreCategoria = models.CharField(max_length=30,blank=True, null=True, verbose_name= 'Nombre categoria')

    def __str__(self):
        return self.nombreCategoria

class producto(models.Model):
    PROD_OFERTA = (
        ('Y', 'SI'),
        ('N', 'NO')
    )

    CATEGORIA = (
        ('Articulos Jardineria', 'Articulos Jardinería'),
        ('Plantas interior', 'Plantas interior'),
        ('Plantas exterior', 'Plantas exterior')
    )

    idProducto = models.IntegerField(primary_key=True, verbose_name= 'Id producto')
    nombreProducto = models.CharField(max_length=150, verbose_name= 'Nombre del producto')
    cantidad = models.PositiveIntegerField(verbose_name='Stock del producto')
    precio = models.PositiveIntegerField(verbose_name='Precio del producto')
    oferta = models.CharField(max_length=1,choices=PROD_OFERTA, default='N',verbose_name='Producto en oferta')
    imagenProducto = models.ImageField(upload_to="images/", null=True, verbose_name='Imagen del producto') 
    categoria = models.ForeignKey(catProducto, on_delete=models.CASCADE)
    descripcion = models.TextField(max_length=1000, verbose_name='Descripcion producto', null=True)

    def __str__(self):
        return self.nombreProducto

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)


ProyectoWeb/Germinar/forms.py
from pickle import NONE
from tkinter import Widget
from django import forms
from django.forms import EmailInput, ModelForm
from .models import producto
from .validators import MaxSizeFileValidator
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ValidationError

class CustomUserCreationForm(UserCreationForm):

    def clean_email(self):
        email = self.cleaned_data["email"]
        existe = User.objects.filter(email__iexact=email).exists()
        if existe:
            raise forms.ValidationError(u'Este correo ya está registrado, intenta ingresando otro')
        return email

    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','password1','password2']


class productoForm(ModelForm):

    def clean_nombre(self):
        nombre = self.cleaned_data["nombre"]
        existe = producto.objects.filter(nombreProducto__iexact=nombre).exists()

        if existe:
            raise ValidationError("Este nombre ya existe")
        
        return nombre

    nombreProducto = forms.CharField(label = 'Nombre del producto', widget = forms.TextInput(
        attrs= {
            'class': 'form-control-lg',
            'placeholder': 'Ingresar nombre del producto',
            'id': 'nombreProducto',
            'required': 'required',
            'max_length': '150',
        }
    ))

    cantidad = forms.IntegerField(label='Cantidad', widget= forms.NumberInput(
        attrs= {
            'class': 'form-control-lg',
            'placeholder': 'Ingresar la cantidad del producto',
            'id': 'cantidad',
            'required': 'required',
            'min': '1'
        }
    ))

    precio = forms.IntegerField(label='Precio', widget= forms.NumberInput(
        attrs= {
            'class': 'form-control-lg',
            'placeholder': 'Ingresar el precio del producto',
            'id': 'precio',
            'required': 'required',
            'min': '1000'
        }
    ))
    
    descripcion = forms.CharField(label='Descripción del producto', widget= forms.Textarea(
        attrs= {
            'role': 'option',
            'class': 'form-control-lg',
            'placeholder': 'Ingresar descripción',
            'id': 'descripcion',
            'required': 'required',
            'max_length': '1000'
        }
    ))
    


    class Meta:
        model = producto

        fields = [
            'nombreProducto',
            'cantidad',
            'precio',
            'imagenProducto',
            'categoria',
            'descripcion'
        ]

        def __init__(self,*args, **kwargs):
            super().__init__(*args, **kwargs)

            self.fields['categoria'].widget.attrs.update({
                'class': 'form-control',
                'placeholder': 'Seleccionar categoría',
                'required': 'required'
            })
        
            self.fields['imagenProducto'].widget.attrs.update({
                'class': 'form-control',
                'type': 'file',
                'label': 'Imagen del producto',
                'validators': [MaxSizeFileValidator(max_file_size=2)]
                
            })

ProyectoWeb/Germinar/views.py
from pyexpat import model
from pyexpat.errors import messages
from django.http import Http404
from django.shortcuts import redirect, render, get_object_or_404
import datetime
from rest_framework.authtoken.models import Token
from requests import Response
from carro.carro import Carro
from .models import producto
from .forms import productoForm, CustomUserCreationForm
from django.urls import reverse
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import Http404
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required, permission_required
from django.conf import settings
import json
import urllib
from .filters import FiltroVista
from django.views.generic import ListView

# Create your views here.

class Persona(object):

    def __init__(self, nombre, apellido):
        self.nombre=nombre
        self.apellido=apellido
        super().__init__()

def principal(request):
    carro=Carro(request)
    return render(request, 'Germinar/principal.html')

@login_required(login_url='/accounts/login/')
def carrito(request):

    return render(request, 'Germinar/carrito.html')

@permission_required('Germinar.change_producto')
def actualizarProducto(request, id ):
    Producto = get_object_or_404(producto,idProducto=id)
    form =  productoForm(instance=Producto)
    context = {
        'form': form,
    }

    if request.method=='POST':
        formulario= productoForm(data=request.POST,files=request.FILES,instance=Producto)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Producto modificado correctamente")
            return redirect(to="listaProductos")
        context['form']= formulario
    return render(request,'Germinar/actualizarProducto.html', context)

@permission_required('Germinar.delete_producto')
def eliminarProducto(request, id):
        Producto = get_object_or_404(producto,idProducto=id)
        Producto.delete()
        return redirect(to='listaProductos')

@permission_required('Germinar.view_producto')
def listaProductos(request):
    productos= producto.objects.all()
    page = request.GET.get('page', 1)
    try:
        paginator = Paginator(productos, 5)
        productos = paginator.page(page)
    except:
        raise Http404

    contexto={
        'entity':productos,
        'paginator': paginator
    }
    return render(request, 'Germinar/listadoProductos.html',contexto)

@permission_required('Germinar.add_producto')
def agregarProducto(request):
    datos= {
        'forms': productoForm(),
    }

    if request.method=='POST':
        formulario= productoForm(data=request.POST, files=request.FILES)
        if formulario.is_valid():
            formulario.save()
            messages.success(request, "Producto añadido correctamente")
            datos['mensaje']="Guardado correctamente"
            return redirect(to='listaProductos')
        else:
            datos["forms"] = formulario

    return render(request, 'Germinar/agregarProducto.html',datos)

def planta(request,id):
    Producto = get_object_or_404(producto,idProducto=id)
    context = {
        'productos': Producto,
    }
    return render(request, 'Germinar/planta.html',context)

def seguimiento(request):

    return render(request, 'Germinar/seguimiento.html')

def base(request):

    return render(request, 'Germinar/base.html')

def formulario(request):
    datos = {
        'form': CustomUserCreationForm()
    }

    if request.method == 'POST':
        formulario = CustomUserCreationForm(data=request.POST)
        if formulario.is_valid():
            recaptcha_response = request.POST.get('g-recaptcha-response')
            url = 'https://www.google.com/recaptcha/api/siteverify'
            values = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response': recaptcha_response
            }
            data = urllib.parse.urlencode(values).encode()
            req =  urllib.request.Request(url, data=data)
            response = urllib.request.urlopen(req)
            result = json.loads(response.read().decode())

            if result['success']:
                formulario.save()
                user = authenticate(username=formulario.cleaned_data["username"], password=formulario.cleaned_data["password1"])
                login(request,user)
                token = Token.objects.get(user=user).key
                messages.success(request, "Te has registrado correctamente")
                return redirect(to="principal")
            else:
                messages.error(request, 'reCaptcha Invalido. Intenta nuevamente')
        datos["form"] = formulario
    return render(request, 'registration/formulario.html',datos)


class Home(ListView):
    model = producto
    template_name = 'Germinar/catalogo.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = FiltroVista(self.request.GET, queryset = self.get_queryset())
        return context
    

ProyectoWeb/Germinar/templates/Germinar/actualizarProducto.html
{% extends "Germinar/base.html" %}
{% block js %}
    <script>
        function modProd(){
            Swal.fire({
                "title": "¡Listo!",
                "width": "600",
                "font-size": "2rem",
                "text": "{{m}}",
                "icon": "success",
                "confirmButtonColor": "#1f4550",
                "padding": "2rem",
                "confirmButtonText": "Ok"
            })
            .then(function(result){
                if(result.isConfirmed) {
                    window.location.href= "{% url 'listaProductos' %}"
                }
            })
        }
    </script>
{% endblock %}
{% block title %} actualizarProducto {% endblock %}
<!DOCTYPE html>
{% block content %}
{% load crispy_forms_tags %}
{% load static %} 
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link type="text/css" rel="preload" href="{% static 'Germinar/css/diseno.css' %}">
    <link type="text/css" rel="stylesheet" href ="{% static 'Germinar/css/diseno.css' %}">
    <link type="text/css" rel="preload" href="{% static 'Germinar/css/normalize.css' %}"> <!--Ayudará en normalizar la vista de la página para todos los navegadores, asi no habrá distinciones entre abrir la página en diferentes navegadores-->
    <link type="text/css" rel="stylesheet" href="{% static 'Germinar/css/normalize.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css" />
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js"></script>
</head>
<script>
    function toggleButton()
    {
        var nombreProd = document.getElementById('nombreProd').value;
        var cantidad = document.getElementById('cantidad').value;
        var precio = document.getElementById('precio').value;
        var categoria = document.getElementById('categoria').value;
        var descripcion = document.getElementById('descripcion').value;
        var seleccionArchivos = document.getElementById('seleccionArchivos').value;
        
        if (nombreProd && cantidad && categoria && precio && descripcion && seleccionArchivos) {
            document.getElementById('submitButton').disabled = false;
        } else {
            document.getElementById('submitButton').disabled = true;
        }
    }
</script>
<body>
    <div class="contenedor-form">
        <div class="contenedor3">
            <div class="subt-pago">
                <h2>Actualizar informaci&oacute;n del producto</h2>
            </div>
                <form action="#" method="POST" enctype="multipart/form-data" class="form-producto contenedor2" name="form-producto" id="form-producto">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <div class="contenedor2">
                        <div class="btn-registrar">
                            <button type="submit" onclick="modProd()" id="submitButton" class="btn-submit btn-primary-listo" >Modificar producto</button>
                        </div>    
                    </div>
                </form> 
        </div>      
    </div>
    <div class="boton-volver contenedor2">
        <button type="button" onclick="history.back('/listaProductos/')"
            class="btn btn-secondary btn-sm">Volver</button>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>
    <script src="{% static 'Germinar/js/script.js' %}"></script>
    <script src="{% static 'Germinar/js/calendario.js' %}"></script>
</body>
</html>
{% endblock %}

ProyectoWeb/Germinar/templates/Germinar/agregarProducto.html
{% extends "Germinar/base.html" %}
{% block title %} agregarProducto {% endblock %}
<!DOCTYPE html>
{% block content %}
{% load crispy_forms_tags %}
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link type="text/css" rel="preload" href="{% static 'Germinar/css/diseno.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'Germinar/css/diseno.css' %}">
    <link type="text/css" rel="preload" href="{% static 'Germinar/css/normalize.css' %}">
    <!--Ayudará en normalizar la vista de la página para todos los navegadores, asi no habrá distinciones entre abrir la página en diferentes navegadores-->
    <link type="text/css" rel="stylesheet" href="{% static 'Germinar/css/normalize.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css" />
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js"></script>
</head>

<script>
    function toggleButton() {
        var nombreProd = document.getElementById('nombreProducto').value;
        var cantidad = document.getElementById('cantidad').value;
        var precio = document.getElementById('precio').value;
        var categoria = document.getElementById('id_categoria').value;
        var descripcion = document.getElementById('descripcion').value;
        var seleccionArchivos = document.getElementById('id_imagenProducto').value;

        if (nombreProd && cantidad && categoria && precio && descripcion && seleccionArchivos) {
            document.getElementById('submitButton').disabled = false;
        } else {
            document.getElementById('submitButton').disabled = true;
        }
    }
</script>

<body>
    <div class="contenedor-form">
        <div class="contenedor3">
            <div class="subt-pago">
                <h2>Agregar producto</h2>
            </div>

            <form action="#" method="post" enctype="multipart/form-data" class="form-producto contenedor2"
                name="form-producto" id="form-producto">
                {% csrf_token %}
                {{forms | crispy}}
                <div class="btn-registrar contenedor2">
                    <button type="submit" id="submitButton" class="btn-submit btn-primary-listo" 
                        value="Enviar">Registrar Producto</button>
                </div>
            </form>
        </div>
    </div>
    </div>
    <div class="boton-volver contenedor2">
        <button type="button" onclick="history.back('/listaProductos/')"
            class="btn btn-secondary btn-sm">Volver</button>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>
    <script src="{% static 'Germinar/js/script.js' %}"></script>
    <script src="{% static 'Germinar/js/calendario.js' %}"></script>
</body>

</html>
{% endblock %}

ProyectoWeb/Germinar/templates/Germinar/carrito.html
{% extends "Germinar/base.html" %}
{% block title %} carrito {% endblock %}
<!DOCTYPE html>
{% block content %}
{% load humanize %}
{% load static %} 
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mi carrito</title>
    <link type="text/css" rel="preload" href="{% static 'Germinar/css/diseno.css' %}">
    <link type="text/css" rel="stylesheet" href ="{% static 'Germinar/css/diseno.css' %}">
    <link type="text/css" rel="preload" href="{% static 'Germinar/css/normalize.css' %}"> <!--Ayudará en normalizar la vista de la página para todos los navegadores, asi no habrá distinciones entre abrir la página en diferentes navegadores-->
    <link type="text/css" rel="stylesheet" href="{% static 'Germinar/css/normalize.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css" />
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js"></script>
</head>
<body style="background-image: linear-gradient(to bottom, #C7D0D8 30%, white 100%);">
    <section class="contenedor3">
        <br>
        <br>
        <h1>Tus productos</h1>
        {% include "carro/widget.html" %}
    </section>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
            integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
            integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
            crossorigin="anonymous"></script>
        <script src="{% static 'Germinar/js/script.js' %}"></script>
</body>
</html>
{% endblock %}

ProyectoWeb/Germinar/templates/Germinar/planta.html
{% extends "Germinar/base.html" %}
{% block title %} Planta {% endblock %}
<!DOCTYPE html>
{% block content %}
{% load humanize %}
{% load static %} 
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Planta</title>
    <link type="text/css" rel="preload" href="{% static 'Germinar/css/diseno.css' %}">
    <link type="text/css" rel="stylesheet" href ="{% static 'Germinar/css/diseno.css' %}">
    <link type="text/css" rel="preload" href="{% static 'Germinar/css/normalize.css' %}"> <!--Ayudará en normalizar la vista de la página para todos los navegadores, asi no habrá distinciones entre abrir la página en diferentes navegadores-->
    <link type="text/css" rel="stylesheet" href="{% static 'Germinar/css/normalize.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.1/themes/base/jquery-ui.css" />
    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.10.1/jquery-ui.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js"></script>
</head>

<body style="background-color: #C7D0D8;">
    <div class="contenedor2">
        <main class="plantas_cuadro contenedor3">
            <div class="planta_img">
                {% if productos.imagenProducto %}
                    <img src="{{productos.imagenProducto.url}}" alt="imagen planta">
                {% endif %}
            </div>
            <div class="planta_info">

                <h1>{{productos.nombreProducto}}</h1>
                <h2>${{productos.precio | intcomma}}</h2>
                <div class="info_cliente">
                    <h3>Stock: {{productos.cantidad}}</h3>
                </div>
                <p>
                    {{productos.descripcion}}
                </p>
                <div class="boton" style="text-align: left;">
                <div class="boton">
                    <a href = "{% url 'carro:agregar' productos.idProducto %}" class="btn-login ">Agregar al carrito</a>
                </div>
            </div>
        </main>
    </div>
    <div class="boton-volver contenedor2">
        <a type="button" href="{% url 'Home'%}" class="btn-login">Volver</a>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>
    <script src="{% static 'Germinar/js/script.js' %}"></script>
    <script src="{% static 'Germinar/js/calendario.js' %}"></script>
</body>
</html>
{% endblock %}